// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6w3Oq8AZSVMq-8jyH1VfSyYcOBVRotU',
    appId: '1:849451849338:web:081a5e1555a29ebc16cdc3',
    messagingSenderId: '849451849338',
    projectId: 'luneva-application',
    authDomain: 'luneva-application.firebaseapp.com',
    storageBucket: 'luneva-application.firebasestorage.app',
    measurementId: 'G-DV6W6BF9CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDk-8KGohyl2ErdN4UrGa7kFHk1inUqYw',
    appId: '1:849451849338:android:4cc99ae169725cf616cdc3',
    messagingSenderId: '849451849338',
    projectId: 'luneva-application',
    storageBucket: 'luneva-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3XYRCpm5Y_rbnVJCTYMN_djbLdU7TIg',
    appId: '1:849451849338:ios:a5e960a10ca7cfcd16cdc3',
    messagingSenderId: '849451849338',
    projectId: 'luneva-application',
    storageBucket: 'luneva-application.firebasestorage.app',
    iosBundleId: 'com.example.lunevaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3XYRCpm5Y_rbnVJCTYMN_djbLdU7TIg',
    appId: '1:849451849338:ios:a5e960a10ca7cfcd16cdc3',
    messagingSenderId: '849451849338',
    projectId: 'luneva-application',
    storageBucket: 'luneva-application.firebasestorage.app',
    iosBundleId: 'com.example.lunevaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw6w3Oq8AZSVMq-8jyH1VfSyYcOBVRotU',
    appId: '1:849451849338:web:05daad255f71200a16cdc3',
    messagingSenderId: '849451849338',
    projectId: 'luneva-application',
    authDomain: 'luneva-application.firebaseapp.com',
    storageBucket: 'luneva-application.firebasestorage.app',
    measurementId: 'G-3173SWVWT4',
  );
}
